plugin: community.general.virtualbox
running_only: true
groups:
  platform_windows: "'windows' in (inventory_hostname)"
  container: "'mini' in (inventory_hostname)"
query:
  logged_in_users: /VirtualBox/GuestInfo/OS/LoggedInUsersList
compose:
  ansible_connection: ('indows' in vbox_Guest_OS)|ternary('winrm', 'ssh')
network_info_path: "/VirtualBox/GuestInfo/Net/1/V4/IP"